### ISSUE TITLE
how can i put all cache data input memory ?

### ISSUE THREAD

**Issue by jefferyship** [gree/flare#99]
i just create memory disk:

mount -t ramfs none /mnt/flare/ -o maxSize=52428800 

the master node which put file to disk  has 1 balance, then the slave node which put file to /mnt/flare/ has 999 balance.

Any advance is appreciate

**Comment by junjihashimoto** [comment]
1, tmpfs 
We use tmpfs instead of ramfs.
These file systems do different behavior when disk is full.
https://www.jamescoyle.net/knowledge/951-the-difference-between-a-tmpfs-and-ramfs-ram-disk

2, memory allocation
Flare does not use VM like JVM, so it does not need many cache memory.
Few giga bytes(2 or 3GB) are enough for system memory.
Allocate almost all memory for tmpfs. 

3, balance
We just use same balances for both master and slave.
In general, balance settings are case by case.
You should try and choose the best value.
